### ISSUE TITLE
.NET 5 does not support @helper directives

### ISSUE THREAD

**Issue by kaspars-ozols** [Geta/geta-optimizely-extensions#14]
How to reproduce:
1. Copy the example from here
https://github.com/Geta/geta-optimizely-extensions#menulist-extension-for-htmlhelper
2. Paste it in any view of .NET 5 project
3. Try to build the project and see the error:

![image](https://user-images.githubusercontent.com/6103815/151534513-974ccd5a-251b-48b8-b278-4fd42bd004e2.png)

**Comment by brianweet** [comment]
Try this instead:
```csharp
@{
    Func<MenuItem, HelperResult> menuItemTemplate =@<li class="@(item.Selected ? "active" : null)">
            @Html.PageLink(item.Page)
        </li>;      
}
```
I will go through the repo docs and update where necessary
