### ISSUE TITLE
GetFriendlyUrl does not include the port in url

### ISSUE THREAD

**Issue by jevgenijsp** [Geta/geta-optimizely-extensions#17]
Is there possible to include also port in the URL?

**Comment by kaspars-ozols** [comment]
The issue was observed when calling `GetFriendlyUrl` and `includeHost` parameter was set to `true`. The site used HTTPS binding and a custom port.

**Comment by brianweet** [comment]
@marisks what do you think about this?
The port is explicitly removed here: https://github.com/Geta/geta-optimizely-extensions/blob/master/src/Geta.Optimizely.Extensions/StringExtensions.cs#L96
Which I understand for default ports (80,443), but I can imagine we'd want to add the port if it's anything other than those two?

**Comment by marisks** [comment]
@brianweet Yep, the port is needed when it is not the default.
